#define MK_KINETIC_SPEED
#define MOUSEKEY_MOVE_DELTA 12
#define MOUSEKEY_INITIAL_SPEED 200
#define MOUSEKEY_BASE_SPEED 1600
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 8
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 24

#define TAPPING_TERM 200

#define FORCE_NKRO

// Disable RGB matrix at startup
#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#undef RGB_MATRIX_DEFAULT_HUE
#define RGB_MATRIX_DEFAULT_HUE 0
#undef RGB_MATRIX_DEFAULT_SAT
#define RGB_MATRIX_DEFAULT_SAT 0
#undef RGB_MATRIX_DEFAULT_VAL
#define RGB_MATRIX_DEFAULT_VAL 0
#undef RGB_MATRIX_KEYPRESSES
